Hardcode mnemonics
Agoric/agoric-3-proposals pull request #133
Opened 2024-03-22 01:55 UTC by LuqiPan

Closes: #5

2024-03-22 15:48 UTC, turadg requested changes
Looking good.

Couple concerns:
- we shouldn't add any files to `.agoric` in the image. That's for validator state. We should actually be removing any files there that aren't in a production chain (optional to do in this PR)
- there shouldn't be any new files in the repo root. The keys are a concern of `synthetic-chain`, not the repo.

We could put the files somewhere else, but I think it would be best not to make these into files. Just set put them as vars in env_setup.sh.

2024-03-25 19:59 UTC, turadg approved these changes

2024-03-26 01:02 UTC, merged

2024-03-27 00:42 UTC, LuqiPan commented
Well, turns out we do have [places](https://github.com/search?q=org%3AAgoric%20%2Froot%2F.agoric%2F&type=code) that depends on, for example, `/root/.agoric/user1.key` be present, namely
- `contract/Makefile` in Agoric/dapp-offer-up
- `contract/Makefile` in Agoric/dapp-agoric-basics
- `proposals/34:upgrade-10/upgradeHelpers.js` in Agoric/agoric-3-proposals

Maybe we can add them back into the container, but not under `/root/.agoric` directory? What do you think, @turadg?

2024-03-27 01:33 UTC, turadg commented
> What do you think, @turadg?

They're hard-coded now so we could copy the keys.

Or put them somewhere else as you suggest, if we want to make it easy for downstream to look them up by name. I'd suggest a place like the upgrade-test-scripts path so that it's more clear they're not part of production