ci(docker): run each platform on a different worker
Agoric/agoric-3-proposals pull request #32
Opened 2023-11-29 16:39 UTC by michaelfig

This is an optimisation to reduce the amount of disk space needed on each worker.

2023-11-30 02:07 UTC, michaelfig commented
Testing and publishing just for linux/amd64:

![image](https://github.com/Agoric/agoric-3-proposals/assets/457244/729ad578-1525-4034-a5a1-4d063ae15efd)

2023-12-05 17:58 UTC, michaelfig commented
This is R4R, having split out the misc cleanups I made into another PR, #39.

2024-01-05 16:33 UTC, mhofman requested changes
I think the failure notification got dropped, probably mistakenly?

Can we add a manual workflow trigger, and test it through that to make sure generating and publishing all platform images works as expected? (I expect that we'll need to add the manual workflow trigger to the `main` branch first)

2024-01-05 16:33 UTC, mhofman commented on .github/workflows/ci.yml
> +          echo "tags=$SUFFIXED" >> $GITHUB_OUTPUT
This is pretty opaque too.

2024-01-05 16:33 UTC, mhofman commented on .github/workflows/ci.yml
> +      packages: write
Why is the explicit permission required here?

2024-01-05 16:33 UTC, mhofman commented on .github/workflows/ci.yml
> -        uses: ./.github/actions/notify-status
This seems to be completely gone, any reason to remove master failure notifications ?

2024-01-10 17:03 UTC, michaelfig commented on .github/workflows/ci.yml
> +            platforms='["'"$DEFAULT_PLATFORM"'"]'
Added a comment.

2024-01-10 17:03 UTC, michaelfig commented on .github/workflows/ci.yml
> +        if: ${{ matrix.platform != env.DEFAULT_PLATFORM }}
I made the setup-qemu unconditional so that we can easily modify the runner configuration without needing to change things in multiple places.

2024-01-10 17:18 UTC, mhofman commented on .github/workflows/ci.yml
> +      - name: Compute tags
Nit, can we move "compute tags" earlier in the job / before the build step so we can easily check the tags before the job completes?

2024-01-10 17:19 UTC, mhofman commented on .github/workflows/ci.yml
> +          echo "tags=$SUFFIXED" >> $GITHUB_OUTPUT
Can we also output to stdout so we can see the computed tag in the logs?

2024-01-10 20:54 UTC, michaelfig commented
> Can we add a manual workflow trigger, and test it through that to make sure generating and publishing all platform images works as expected? (I expect that we'll need to add the manual workflow trigger to the `main` branch first)

https://github.com/Agoric/agoric-3-proposals/actions shows both the manual and PR triggers working correctly.

2024-01-10 20:57 UTC, michaelfig commented
> both the manual and PR triggers

That is, the [manual](https://github.com/Agoric/agoric-3-proposals/actions/runs/7479870918) and [PR](https://github.com/Agoric/agoric-3-proposals/actions/runs/7479865387) runs.

2024-01-10 23:21 UTC, turadg commented on .github/workflows/ci.yml
> +    # Run on our own self-hosted ARM64 machine if the platform is ARMish.
where is operation of this machine documented?

2024-01-11 19:00 UTC, mhofman approved these changes
Seeing the manual run results, I'm confident this does what it claims it does!

2024-01-11 23:01 UTC, merged